# rollout-app.yaml
# from & use https://github.com/argoproj/rollouts-demo.git
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/argoproj/rollouts-demo.git
    targetRevision: HEAD
    path: examples/blue-green
  syncPolicy:
    automated:
      prune: true
      selfHeal: true