name: Build

on: 
  push:
    branches: ["main"]
  workflow_dispatch:
    
jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
  
  setUpGo:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/setup-go@v4

  printArgs:
    runs-on: ubuntu-latest
    needs: setUpGo
    steps:
      - run: go run hello.go Bonjour le monde

  