name: "Exemple de workflow"
on:
  push:
    branches:
      - main

jobs:
  greet-user:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install
      run: npm i

    - name: Dire bonjour
      uses: ./my-custom-action-js
      with:
        username: "Jean"
        greeting: "Salut"